# Generated by Django 5.0.1 on 2024-02-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Answers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assesment_Areas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=100)),
                ('Subject_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sydney_Participants', models.IntegerField()),
                ('Sydney_Percentile', models.IntegerField()),
                ('Correct_answer_precentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Correct_Answer', models.CharField(max_length=1)),
                ('Participant', models.IntegerField()),
                ('Student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Category_Id', models.CharField(max_length=100)),
                ('Year_level_name', models.CharField(max_length=100)),
                ('Correct_answer_id', models.CharField(max_length=1)),
                ('Answer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.answers')),
                ('Assesment_Area_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.assesment_areas')),
                ('Award_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.awards')),
                ('Class_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.class')),
                ('School_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.school')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
                ('Subject_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
            ],
        ),
    ]
